"""Generate ``reports/RESULTS.md`` from the artifacts on disk.

Generated, never hand-typed, so the document cannot drift away from what the
pipeline actually produced.
"""

from __future__ import annotations

import json
import logging
from pathlib import Path

import pandas as pd

from nuance.config import Config, load_config

log = logging.getLogger(__name__)


def _table(df: pd.DataFrame, cols: list[str], nd: int = 3) -> str:
    d = df[cols].copy()
    for c in d.columns:
        if pd.api.types.is_float_dtype(d[c]):
            d[c] = d[c].round(nd)
    head = "| " + " | ".join(cols) + " |"
    rule = "| " + " | ".join("---" for _ in cols) + " |"
    rows = ["| " + " | ".join(str(v) for v in r) + " |" for r in d.itertuples(index=False)]
    return "\n".join([head, rule, *rows])


def _ci(m: dict, key: str = "macro_f1") -> str:
    return f"{m[key]:.4f} [{m[f'{key}_ci_low']:.4f}, {m[f'{key}_ci_high']:.4f}]"


def write_results_markdown(cfg: Config | None = None) -> Path:
    cfg = cfg or load_config()
    reports = cfg.resolve(cfg.paths.reports_dir)

    def load_json(name):
        p = reports / name
        return json.loads(p.read_text()) if p.exists() else {}

    def load_csv(name):
        p = reports / name
        return pd.read_csv(p) if p.exists() else pd.DataFrame()

    metrics = load_json("model_metrics.json")
    audit = load_json("audit_metrics.json")
    transfer_meta = load_json("transfer_metrics.json")
    per_label = load_csv("per_label.csv")
    transfer = load_csv("transfer.csv")
    confusions = load_csv("confusion_pairs.csv")
    support = load_csv("label_support.csv")
    budget = load_csv("active_budget.csv")

    champion = "wordchar_logistic"
    head = metrics["ladder"][champion]
    lines: list[str] = []
    a = lines.append

    a("# Results\n")
    a(
        "_Generated by `nuance report`. Every number comes from a file in "
        "`reports/`; nothing is transcribed by hand._\n"
    )

    # ---------------------------------------------------------------- headline
    a("## Headline\n")
    a(
        f"- **macro-F1 {_ci(head)}** on {head['n']:,} held-out comments across "
        f"{head['n_labels']} labels — an interval **{head['macro_f1_ci_width']:.3f}** wide."
    )
    a(f"- **micro-F1 {_ci(head, 'micro_f1')}**.")
    a(
        f"- Only **{head['n_labels_measurable']} of {head['n_labels']}** labels have the "
        f"{head['min_support_measurable']}+ held-out positives needed for a per-label "
        f"score to be a measurement. Restricted to those, macro-F1 is "
        f"**{_ci(head, 'macro_f1_measurable')}** — higher, and with an interval "
        f"**{head['macro_f1_ci_width'] / head['macro_f1_measurable_ci_width']:.1f}x** "
        f"tighter."
    )
    if not per_label.empty:
        worst = per_label.sort_values("f1_ci_width", ascending=False).iloc[0]
        a(
            f"- The widest per-label interval belongs to `{worst['label']}` "
            f"({int(worst['support'])} held-out examples): F1 {worst['f1']:.3f}, "
            f"95% CI [{worst['f1_ci_low']:.3f}, {worst['f1_ci_high']:.3f}]."
        )
    a("")

    # ------------------------------------------------------------------ ladder
    a("## The model ladder\n")
    rows = [
        {
            "model": k,
            "macro_f1": v["macro_f1"],
            "ci_low": v["macro_f1_ci_low"],
            "ci_high": v["macro_f1_ci_high"],
            "micro_f1": v["micro_f1"],
            "seconds": v.get("seconds"),
        }
        for k, v in metrics["ladder"].items()
    ]
    a(
        _table(
            pd.DataFrame(rows), ["model", "macro_f1", "ci_low", "ci_high", "micro_f1", "seconds"], 4
        )
    )
    a(
        "\nAll at the conventional 0.5 threshold. A base-rate predictor scores exactly "
        "zero there, because no label's base rate reaches 0.5 — a reminder that 0.5 is "
        "a decision, not a neutral default.\n"
    )

    # ------------------------------------------------------------------ paired
    a("### What is actually distinguishable\n")
    p = pd.DataFrame(metrics["paired"]).T.reset_index(names="comparison")
    a(_table(p, ["comparison", "a", "b", "difference", "ci_low", "ci_high", "significant"], 4))
    a(
        "\nPaired on identical bootstrap resamples. This matters: the character-n-gram "
        "model and the word-only model have heavily overlapping individual intervals, "
        "and the paired test still separates them cleanly — because two systems scored "
        "on the same comments share most of their noise, and pairing cancels it.\n"
    )

    # --------------------------------------------------------------- thresholds
    a("## Threshold strategies\n")
    d = pd.DataFrame(metrics["decoders"]).T.reset_index(names="strategy")
    a(
        _table(
            d,
            [
                "strategy",
                "macro_f1",
                "macro_f1_ci_low",
                "macro_f1_ci_high",
                "micro_f1",
                "fitted_on",
            ],
            4,
        )
    )
    dev_vs_flat = metrics["paired"].get("per_label_dev_vs_flat", {})
    oof_vs_flat = metrics["paired"].get("per_label_oof_vs_flat", {})
    a(
        f"\nTuning a threshold per label on the dev split — the standard recipe — "
        f"comes out **{dev_vs_flat.get('difference', 0):+.4f}** against leaving every "
        f"threshold at 0.5 "
        f"(95% CI [{dev_vs_flat.get('ci_low', 0):+.4f}, "
        f"{dev_vs_flat.get('ci_high', 0):+.4f}]). Cross-fitting the same tuning on "
        f"out-of-fold training predictions, where the rare labels have several times "
        f"more positives to tune on, recovers most of that: "
        f"**{oof_vs_flat.get('difference', 0):+.4f}** "
        f"(95% CI [{oof_vs_flat.get('ci_low', 0):+.4f}, "
        f"{oof_vs_flat.get('ci_high', 0):+.4f}])."
    )
    a(
        "\nNeither is distinguishable from doing nothing. The honest summary is that on "
        "this benchmark threshold tuning is a coin flip dressed as a method — and the "
        "version most people use is the one that lands on the wrong side of it.\n"
    )
    a("![threshold strategies](figures/threshold_strategies.png)\n")

    # ------------------------------------------------------------- per-label
    a("## The scoreboard nobody prints\n")
    if not per_label.empty:
        a(
            _table(
                per_label.sort_values("support").head(10),
                [
                    "label",
                    "support",
                    "precision",
                    "recall",
                    "f1",
                    "f1_ci_low",
                    "f1_ci_high",
                    "measurable",
                ],
                3,
            )
        )
        s = metrics["per_label_summary"]
        a(
            f"\nMedian interval width: **{s['median_ci_width_rare']:.3f}** for labels "
            f"below the support threshold against **{s['median_ci_width_common']:.3f}** "
            f"above it. These labels are not being scored badly; they are barely being "
            f"scored.\n"
        )
    a("![per-label F1](figures/per_label_f1.png)\n")

    # --------------------------------------------------------------- taxonomy
    a("## The same model, three taxonomies\n")
    coarse = metrics["errors"]["coarse"]
    rows = [
        {
            "taxonomy": "27 emotions + neutral",
            "labels": head["n_labels"],
            "rarest label": int(support["test"].min()) if not support.empty else None,
            "macro_f1": head["macro_f1"],
            "micro_f1": head["micro_f1"],
        }
    ]
    for view, label in (
        ("ekman", "6 Ekman families + neutral"),
        ("sentiment", "positive / negative / ambiguous / neutral"),
    ):
        c = coarse[view]
        rows.append(
            {
                "taxonomy": label,
                "labels": c["n_labels"],
                "rarest label": c["min_support"],
                "macro_f1": c["macro_f1"],
                "micro_f1": c["micro_f1"],
            }
        )
    a(_table(pd.DataFrame(rows), ["taxonomy", "labels", "rarest label", "macro_f1", "micro_f1"], 4))
    a(
        "\nIdentical predictions, scored against coarser questions. Nothing about the "
        "model changed.\n"
    )
    a("![taxonomy views](figures/taxonomy_views.png)\n")

    # ----------------------------------------------------------------- errors
    a("## Where the errors land\n")
    fam = metrics["errors"]["family_split"]
    a(
        f"- **{fam['share_within_family']:.1%}** of substitutions stay inside the same "
        f"Ekman family ({fam['within_family']:,} of {fam['substitution_errors']:,})."
    )
    a(
        f"- **{fam['share_involving_neutral']:.1%}** involve `neutral` in one direction "
        f"or the other.\n"
    )
    a(
        "So the fine-grained taxonomy is not the main difficulty. The hard boundary is "
        "whether a comment carries any emotion at all — which is exactly the judgement "
        "human annotators disagree about most.\n"
    )
    if not confusions.empty:
        a(_table(confusions.head(8), ["true", "predicted_instead", "count"], 0))
        a("")
    a("![confusions](figures/confusions.png)\n")

    # ------------------------------------------------------------------ audit
    if audit:
        a("## Are the labels even right?\n")
        fam2 = audit.get("family_breakdown", {})
        retrain = audit.get("retrain_without_suspects", {})
        a(
            f"Confident learning on out-of-fold predictions flags "
            f"**{audit['flagged']:,}** assignments for review. Of the "
            f"'label probably missing' flags, **{fam2.get('share_same_family', 0):.0%}** "
            f"name an emotion in the same Ekman family as one the comment already "
            f"carries — a shade rather than an error.\n"
        )
        examples = pd.DataFrame(audit.get("examples", []))
        if not examples.empty:
            a(_table(examples.head(6), ["text", "given_labels", "label", "kind"], 3))
            a("")
        a(
            f"Dropping every implicated row — **{retrain.get('rows_dropped', 0):,}**, "
            f"{retrain.get('share_of_training_set', 0):.0%} of the training set — and "
            f"retraining moves macro-F1 from {retrain.get('macro_f1_before', 0):.4f} to "
            f"{retrain.get('macro_f1_after', 0):.4f}: "
            f"{'a significant change' if retrain.get('paired', {}).get('significant') else 'not distinguishable from noise'}. "
            f"The audit earns its place by finding labels worth fixing, not by raising "
            f"the score.\n"
        )
        a("![label noise](figures/label_noise.png)\n")

    # --------------------------------------------------------------- transfer
    if not transfer.empty:
        a("## Does it travel?\n")
        lk = transfer_meta.get("leakage", {})
        if lk:
            a(
                f"NLTK's tweet labels come from emoticons **still present in the "
                f"text**: {lk['share_decidable_by_emoticon_alone']:.1%} of tweets are "
                f"decidable from the emoticon alone, at "
                f"{lk['accuracy_of_emoticon_rule_where_it_fires']:.0%} accuracy where "
                f"the rule fires. Evaluating without stripping them measures emoticon "
                f"detection.\n"
            )
        a(_table(transfer, ["model", "evaluated_on", "emoticons", "n", "accuracy", "f1"], 3))
        a("\n![transfer](figures/transfer.png)\n")

    # ----------------------------------------------------------------- budget
    if not budget.empty:
        a("## What the annotation budget bought\n")
        a(
            _table(
                budget, ["strategy", "full_data_macro_f1", "budget_reached", "share_of_corpus"], 4
            )
        )
        a(
            "\nUncertainty sampling is indistinguishable from labelling at random here, "
            "and the curve is still climbing at the full 43,410 comments. On this "
            "problem more data would help more than cleverer selection of it.\n"
        )
        a("![active learning](figures/active_learning.png)\n")

    out = reports / "RESULTS.md"
    out.write_text("\n".join(lines))
    log.info("wrote %s", out)
    return out
